### ISSUE TITLE
CocoaPods support in general

### ISSUE THREAD

**Issue by alloy** [ReactExtensionManager/rem#5]
Hey, I’m loving that you decided to use CocoaPods :heart: 

* Regarding installation, I can imagine that your users might not want to deal with Ruby installation issues, in which case you might want to point them to our recently started effort to provide a complete bundled installation: https://github.com/CocoaPods/CocoaPods-app
* “If two modules depend on two different versions of the same CocoaPod, then there is no way to correctly build the project.” Can you elaborate on what this issue is about? Is this simply about hard version requirements?
* Going forward, it might make sense for us to work closer and provide answers to your needs. Would you (and others on your team) like to have access to our Slack channel? If so, send me your email addresses.

**Comment by ide** [comment]
Hi @alloy, really great to hear from the CocoaPods team! Thanks for the pointer to the new installer -- it's now mentioned in the setup section of the readme.

About the "If two modules depend on two different versions..." sentence, we just meant that we can't build the project if one module needs CocoaLumberjack ~> 1.0 and another wants ~> 2.0, for example. This is new to a lot of JS developers because the way Node works, you can have several copies of the same npm package. Sorry that wasn't clear - we'll improve the docs.

And thanks for the offer to join your Slack channel. Will send you a message shortly.

**Comment by alloy** [comment]
> About the "If two modules depend on two different versions..." sentence, we just meant that we can't build the project if one module needs CocoaLumberjack ~> 1.0 and another wants ~> 2.0, for example. This is new to a lot of JS developers because the way Node works, you can have several copies of the same npm package. Sorry that wasn't clear - we'll improve the docs.

Ah right, from that point of view. Makes sense :+1:

**Comment by alloy** [comment]
> Unlike with NPM/JS, native iOS code cannot contain different versions of the same library in 1 application. Therefore, an extension that relies on e.g. `CocoaLumberjack 1.x` and another extension relies on `CocoaLumberjack 2.x` will not be able to coexist.

**Comment by paramaggarwal** [comment]
@alloy Discovered `Cocoapods.app` from here. Absolutely love it. :heart: I have been using it on the Cli since a year, and am very glad to see this app. Thanks you so much to you and the rest of the team!

Please publicise this more on the CocoaPods homepage! (you can say `Beta` if this is not fully ready).

**Comment by alloy** [comment]
@paramaggarwal Hah, good to hear! It’s listed on https://cocoapods.org/about, but I’m sure there will be more/better release communication in the future.

**Comment by paramaggarwal** [comment]
@alloy Oh! I have never clicked on that About page. This needs to be the homepage!!!
